extends SceneTree
## Exports one generation brief per unit + per valley into art_workbench/tasks/,
## composed from data/units/*.tres (art_notes) + the order style blocks below.
## This is the sync mechanism (AI_ART_PIPELINE.md §11): character data is the
## single source of truth; briefs are generated, never hand-written.
## Run:  godot --headless --path . -s res://tools/export_art_tasks.gd

const STYLE_BLOCK := "stylized anime, painterly rendering, clean lineart, deep lapis blue and gold palette, ornamental rim light, dignified, mobile game character art"

## Per-order costume/mood blocks — GDD §3.5. Edit here AND in the GDD together.
const ORDER_BLOCKS := {
	"Naqshbandi": "understated small turban, plain deep emerald robes, silent composed presence, concentric circles of soft light",
	"Qadiri": "turquoise turban and trim, storm-grey layered robes, thunder and sound-ring motifs, commanding presence",
	"Rifai": "iron-black turban or head-wrap, deep red robes with scorched leather and chain accents, ember glow, unshakeable stance",
	"Mevlevi": "tall honey-colored felt sikke cap, flowing white tennure whirling skirt, black hirka cloak, spiral wind trails",
	"Shadhili": "deep royal-blue and white robes, prayer beads, tidewater and wave motifs, calm protective presence",
	"Chishti": "warm rose and ochre robes, musical geometry motifs, daf frame drum, radiating warmth and welcome",
	"Suhrawardi": "pale gold and sun-ray patterned robes, lenses and beams of light, precise illuminated presence",
	"": "demon of black shadow veined with blood-red corrupted light, no human features, fantasy folklore register",  # enemies
}

const NEGATIVE_NOTES := "NO text, NO Arabic or pseudo-Arabic script, NO calligraphy glyphs (hard rule — AI_ART_PIPELINE.md §0.3), no sacred imagery, modest dress always. Cultural-accuracy check against real regional dress references before any LoRA training."


func _initialize() -> void:
	var db: Node = root.get_node_or_null("Db")
	if db == null:
		db = preload("res://scripts/systems/database.gd").new()
		db.name = "Db"
		root.add_child(db)
	db.reload()
	DirAccess.make_dir_recursive_absolute("res://art_workbench/tasks")

	var index: Array = []
	var ids: Array = db.units.keys()
	ids.sort()
	for id in ids:
		var u: UnitData = db.units[id]
		var brief := _unit_brief(id, u)
		var path := "res://art_workbench/tasks/%s.md" % id
		FileAccess.open(path, FileAccess.WRITE).store_string(brief)
		index.append("- [%s] %s — %s" % [_status(id), u.label(), path])
		print("brief: ", id)

	var summary := "# Art task index (generated — do not edit)\n\nRegenerate: `godot --headless --path . -s res://tools/export_art_tasks.gd`\nAudit:      `godot --headless --path . -s res://tools/audit_assets.gd`\n\n"
	summary += "\n".join(index) + "\n"
	FileAccess.open("res://art_workbench/tasks/INDEX.md", FileAccess.WRITE).store_string(summary)
	print("DONE — briefs in art_workbench/tasks/")
	quit(0)


func _status(id: String) -> String:
	var have := 0
	for kind in ["portrait", "chibi", "icon"]:
		if FileAccess.file_exists("res://assets/art/units/%s/%s.png" % [id, kind]):
			have += 1
	return "%d/3" % have


func _unit_brief(id: String, u: UnitData) -> String:
	var color: Color = Enums.AFFINITY_COLORS[u.affinity]
	var skill_names: Array = []
	for s: SkillData in u.skills:
		skill_names.append(s.full_name())
	var prompt := "%s, %s, %s, signature color #%s accents" % [
		STYLE_BLOCK, ORDER_BLOCKS.get(u.order_name, ORDER_BLOCKS[""]),
		u.art_notes if u.art_notes != "" else "(no art_notes set in data/units/%s.tres — add them!)" % id,
		color.to_html(false)]
	var lines := [
		"# Art brief — %s  (`%s`)" % [u.label(), id],
		"",
		"Generated from `data/units/%s.tres` — edit `art_notes` there, then regenerate. Do not edit this file." % id,
		"",
		"| | |",
		"|---|---|",
		"| Order | %s |" % (u.order_name if u.order_name != "" else "— (demon)"),
		"| Rarity | %s (%d*) |" % [Enums.RARITY_NAMES.get(u.rarity, "?"), u.rarity],
		"| Affinity | %s — #%s |" % [Enums.AFFINITY_NAMES[u.affinity], color.to_html(false)],
		"| Abilities (for pose/VFX ideas) | %s |" % ", ".join(skill_names),
		"",
		"## Required files (drop via tools/import_art.sh)",
		"- `assets/art/units/%s/portrait.png` — 1024px, bust, transparent or dark bg" % id,
		"- `assets/art/units/%s/chibi.png` — 512px, full body A-pose, flat shading (playable units)" % id,
		"- `assets/art/units/%s/icon.png` — 256px square crop of the face" % id,
		"",
		"## Base generation prompt",
		"```",
		prompt,
		"```",
		"",
		"## Hard rules",
		NEGATIVE_NOTES,
		"",
		"## Pipeline (AI_ART_PIPELINE.md §3)",
		"explore -> lock design -> cultural check -> reference sheet -> LoRA (`" + id.replace("_", "") + "4x` trigger) -> production -> paint-over -> import -> audit",
	]
	return "\n".join(lines) + "\n"
